### ISSUE TITLE
Missing dataset and checkpints

### ISSUE THREAD

**Issue by engr3os** [asheshjain399/ICCV2015_Brain4Cars#1]
Hi,

Could you please provide the sample dataset and checkpoint for the maneuvering prediction task?  I can't find the dataset.

Thanks,

**Comment by asheshjain399** [comment]
We have currently released our feature vectors, training and test code, and the trained models for reproducing our results in the "reproduce_results" directory. We will soon release the raw videos. 

Just a note that the overall data set is pretty big, so we need to figure its hosting requirements.

**Comment by asheshjain399** [comment]
Data is now available for download. Pls check the readme.

**Comment by engr3os** [comment]
Thanks.

On Wed, Dec 2, 2015 at 10:20 AM, Ashesh Jain notifications@github.com
wrote:

> Data is now available for download. Pls check the readme.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/asheshjain399/ICCV2015_Brain4Cars/issues/1#issuecomment-161388244
> .

## 

Regards,
Oluwatobi Olabiyi

No one ever attain very eminent success in life by doing only what is
required of him, it is the amount of that which is over and above the
required that determines the greatness of ultimate distinction
